### ISSUE TITLE
Naslov v README datoteki

### ISSUE THREAD

**Issue by katjabercic** [Kloc-cpu/racunalniski-praktikum#1]
V README.md datoteki v prvi vrstici piše `# Racunalniški praktikum`, moralo bi pisati `# Računalniški praktikum`. Če popravite, boste dobili točko.

Lep pozdrav,
Katja

**Comment by Kloc-cpu** [comment]
Pozdravljeni,

Problem sem odpravil.
Za lažji dostop vam pošiljam tudi link:
https://github.com/Kloc-cpu/racunalniski-praktikum.

Zahvaljujem se vam za opomnik in potrpežljivost.

Lep pozdrav,
Klemen Žukovec

V V pet., 11. okt. 2024 ob 11:18 je oseba Katja Berčič <
***@***.***> napisala:
